# Generated by Django 2.1.8 on 2019-06-11 05:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190611_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 11, 5, 6, 8, 932372, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
    ]
