# Generated by Django 2.1.8 on 2019-06-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='hash_tags',
            field=models.ManyToManyField(blank=True, related_name='post_tagged', to='posts.HashTag'),
        ),
    ]
