# Generated by Django 2.1.8 on 2019-06-12 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_content1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content1',
        ),
    ]
