# Generated by Django 2.1.8 on 2019-06-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
    ]
